[package]
name = "surrealqb"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.30"
serde = { version="1.0.204", features = ["derive"] }
serde_json = "1.0.120"
surrealdb = { version="1.5.4", features = ["sql2","arbitrary"] }
tokio = "1.38.0"
